const jobs = [
    {
        id: 1,
        title: "Full Stack Developer",
        company: "TechCorp",
        location: "San Francisco, CA",
        category: "Engineering",
        type: "Full-time",
        salary: 120000,
        description:
            "We are looking for a Full Stack Developer proficient in JavaScript, React, and Node.js.",
        requirements: [
            "5+ years experience with JavaScript",
            "3+ years experience with React",
            "Experience with Node.js and Express",
            "Knowledge of SQL and NoSQL databases",
        ],
        postedAt: "2025-03-15T09:00:00Z",
        contact: "careers@techcorp.com",
    },
    {
        id: 2,
        title: "UX/UI Designer",
        company: "DesignHub",
        location: "New York, NY",
        category: "Design",
        type: "Full-time",
        salary: 95000,
        description:
            "Seeking a talented UX/UI Designer to create beautiful and functional interfaces for our products.",
        requirements: [
            "3+ years of UX/UI design experience",
            "Proficiency in Figma and Adobe Creative Suite",
            "Understanding of user-centered design principles",
            "Portfolio showcasing previous work",
        ],
        postedAt: "2025-03-20T14:30:00Z",
        contact: "jobs@designhub.com",
    },
    {
        id: 3,
        title: "Data Scientist",
        company: "DataInc",
        location: "Remote",
        category: "Data",
        type: "Full-time",
        salary: 130000,
        description:
            "Join our data team to build machine learning models and extract insights from complex datasets.",
        requirements: [
            "MS or PhD in Computer Science, Statistics, or related field",
            "Experience with Python, TensorFlow, and PyTorch",
            "Knowledge of statistical methods and machine learning algorithms",
            "Experience with big data technologies",
        ],
        postedAt: "2025-03-18T11:15:00Z",
        contact: "hiring@datainc.com",
    },
    {
        id: 4,
        title: "DevOps Engineer",
        company: "CloudSys",
        location: "Seattle, WA",
        category: "Operations",
        type: "Full-time",
        salary: 115000,
        description:
            "Looking for a DevOps Engineer to build and maintain our cloud infrastructure and CI/CD pipelines.",
        requirements: [
            "3+ years experience with AWS or Azure",
            "Knowledge of Docker and Kubernetes",
            "Experience with CI/CD tools like Jenkins or GitHub Actions",
            "Scripting skills in Python, Bash, or similar",
        ],
        postedAt: "2025-03-10T08:45:00Z",
        contact: "jobs@cloudsys.com",
    },
    {
        id: 5,
        title: "Product Manager",
        company: "ProductLabs",
        location: "Austin, TX",
        category: "Product",
        type: "Full-time",
        salary: 110000,
        description:
            "We need a Product Manager to oversee product development from conception to launch.",
        requirements: [
            "5+ years of product management experience",
            "Strong analytical and problem-solving skills",
            "Excellent communication and leadership abilities",
            "Experience with Agile methodologies",
        ],
        postedAt: "2025-03-22T10:00:00Z",
        contact: "careers@productlabs.com",
    },
    {
        id: 6,
        title: "Frontend Developer",
        company: "WebFront",
        location: "Boston, MA",
        category: "Engineering",
        type: "Full-time",
        salary: 95000,
        description:
            "Looking for a Frontend Developer with expertise in React and modern JavaScript.",
        requirements: [
            "3+ years experience with React",
            "Strong knowledge of HTML5, CSS3, and JavaScript",
            "Experience with state management (Redux, MobX, etc.)",
            "Understanding of responsive web design",
        ],
        postedAt: "2025-03-19T13:20:00Z",
        contact: "hiring@webfront.com",
    },
    {
        id: 7,
        title: "Backend Engineer",
        company: "ServerTech",
        location: "Chicago, IL",
        category: "Engineering",
        type: "Full-time",
        salary: 105000,
        description:
            "Join our team to build scalable and efficient backend systems.",
        requirements: [
            "4+ years experience with Node.js or Python",
            "Knowledge of SQL and NoSQL databases",
            "Experience with RESTful API design",
            "Understanding of cloud services (AWS, GCP, or Azure)",
        ],
        postedAt: "2025-03-17T15:45:00Z",
        contact: "careers@servertech.com",
    },
    {
        id: 8,
        title: "Marketing Specialist",
        company: "GrowthCo",
        location: "Miami, FL",
        category: "Marketing",
        type: "Full-time",
        salary: 80000,
        description:
            "Seeking a Marketing Specialist to develop and execute marketing strategies.",
        requirements: [
            "3+ years of marketing experience",
            "Experience with digital marketing channels",
            "Knowledge of marketing analytics tools",
            "Strong written and verbal communication skills",
        ],
        postedAt: "2025-03-21T09:30:00Z",
        contact: "jobs@growthco.com",
    },
    {
        id: 9,
        title: "QA Engineer",
        company: "QualityTech",
        location: "Denver, CO",
        category: "Engineering",
        type: "Full-time",
        salary: 90000,
        description:
            "Join our QA team to ensure the quality of our software products.",
        requirements: [
            "3+ years of software testing experience",
            "Experience with automated testing tools",
            "Knowledge of testing methodologies",
            "Strong attention to detail",
        ],
        postedAt: "2025-03-16T11:00:00Z",
        contact: "hr@qualitytech.com",
    },
    {
        id: 10,
        title: "Technical Writer",
        company: "DocsInc",
        location: "Portland, OR",
        category: "Content",
        type: "Full-time",
        salary: 75000,
        description:
            "We need a Technical Writer to create clear and concise documentation for our products.",
        requirements: [
            "2+ years of technical writing experience",
            "Excellent written communication skills",
            "Ability to translate complex technical concepts into clear documentation",
            "Familiarity with markdown and documentation tools",
        ],
        postedAt: "2025-03-14T14:15:00Z",
        contact: "jobs@docsinc.com",
    },
    {
        id: 11,
        title: "Mobile Developer (iOS)",
        company: "AppWorks",
        location: "Los Angeles, CA",
        category: "Engineering",
        type: "Full-time",
        salary: 110000,
        description:
            "Looking for an iOS Developer to build and maintain our mobile applications.",
        requirements: [
            "4+ years of iOS development experience",
            "Proficiency in Swift and Objective-C",
            "Experience with iOS frameworks and libraries",
            "Understanding of Apple's design principles",
        ],
        postedAt: "2025-03-23T08:00:00Z",
        contact: "careers@appworks.com",
    },
    {
        id: 12,
        title: "Project Manager",
        company: "ProjectPro",
        location: "Washington, DC",
        category: "Management",
        type: "Full-time",
        salary: 95000,
        description:
            "We're hiring a Project Manager to oversee the planning and execution of technical projects.",
        requirements: [
            "5+ years of project management experience",
            "PMP certification preferred",
            "Experience with project management tools",
            "Strong leadership and communication skills",
        ],
        postedAt: "2025-03-12T10:30:00Z",
        contact: "jobs@projectpro.com",
    },
    {
        id: 13,
        title: "System Administrator",
        company: "SysOps",
        location: "Phoenix, AZ",
        category: "Operations",
        type: "Full-time",
        salary: 85000,
        description:
            "Join our team to manage and maintain our IT infrastructure.",
        requirements: [
            "3+ years of system administration experience",
            "Knowledge of Linux/Unix and Windows Server",
            "Experience with virtualization technologies",
            "Understanding of network security principles",
        ],
        postedAt: "2025-03-18T09:45:00Z",
        contact: "careers@sysops.com",
    },
    {
        id: 14,
        title: "Cybersecurity Analyst",
        company: "SecureNet",
        location: "Atlanta, GA",
        category: "Security",
        type: "Full-time",
        salary: 120000,
        description:
            "Looking for a Cybersecurity Analyst to protect our systems and data from threats.",
        requirements: [
            "4+ years of cybersecurity experience",
            "Relevant certifications (CISSP, CEH, etc.)",
            "Experience with security tools and technologies",
            "Knowledge of security frameworks and best practices",
        ],
        postedAt: "2025-03-15T13:00:00Z",
        contact: "jobs@securenet.com",
    },
    {
        id: 15,
        title: "Database Administrator",
        company: "DataBase",
        location: "Dallas, TX",
        category: "Data",
        type: "Full-time",
        salary: 95000,
        description:
            "Seeking a Database Administrator to manage and optimize our database systems.",
        requirements: [
            "5+ years of database administration experience",
            "Proficiency in SQL and database technologies",
            "Experience with performance tuning and optimization",
            "Knowledge of backup and recovery strategies",
        ],
        postedAt: "2025-03-20T11:30:00Z",
        contact: "careers@database.com",
    },
    {
        id: 16,
        title: "Content Strategist",
        company: "ContentCo",
        location: "Remote",
        category: "Marketing",
        type: "Full-time",
        salary: 85000,
        description:
            "Join our team to develop and execute content strategies that engage our audience.",
        requirements: [
            "3+ years of content strategy experience",
            "Strong writing and editing skills",
            "Experience with SEO and content marketing",
            "Ability to analyze content performance metrics",
        ],
        postedAt: "2025-03-17T10:15:00Z",
        contact: "hr@contentco.com",
    },
    {
        id: 17,
        title: "Machine Learning Engineer",
        company: "AICompany",
        location: "Seattle, WA",
        category: "Data",
        type: "Full-time",
        salary: 140000,
        description:
            "We're looking for a Machine Learning Engineer to develop AI solutions for our products.",
        requirements: [
            "MS or PhD in Computer Science or related field",
            "3+ years of machine learning experience",
            "Proficiency in Python and ML frameworks",
            "Experience with deep learning and neural networks",
        ],
        postedAt: "2025-03-22T14:00:00Z",
        contact: "jobs@aicompany.com",
    },
    {
        id: 18,
        title: "Human Resources Manager",
        company: "PeopleFirst",
        location: "Minneapolis, MN",
        category: "HR",
        type: "Full-time",
        salary: 90000,
        description:
            "Seeking an HR Manager to oversee recruitment, employee relations, and HR operations.",
        requirements: [
            "5+ years of HR experience",
            "Knowledge of HR policies and practices",
            "Strong interpersonal and communication skills",
            "Experience with HRIS systems",
        ],
        postedAt: "2025-03-19T09:00:00Z",
        contact: "careers@peoplefirst.com",
    },
    {
        id: 19,
        title: "Blockchain Developer",
        company: "ChainTech",
        location: "Remote",
        category: "Engineering",
        type: "Full-time",
        salary: 130000,
        description:
            "Join our team to develop blockchain solutions for our financial products.",
        requirements: [
            "3+ years of blockchain development experience",
            "Proficiency in Solidity and smart contract development",
            "Understanding of blockchain protocols and consensus mechanisms",
            "Experience with web3.js or ethers.js",
        ],
        postedAt: "2025-03-21T11:45:00Z",
        contact: "jobs@chaintech.com",
    },
    {
        id: 20,
        title: "Customer Success Manager",
        company: "ClientCare",
        location: "San Diego, CA",
        category: "Customer Service",
        type: "Full-time",
        salary: 80000,
        description:
            "Looking for a Customer Success Manager to ensure client satisfaction and retention.",
        requirements: [
            "3+ years of customer success or account management experience",
            "Strong relationship-building skills",
            "Experience with CRM software",
            "Excellent problem-solving abilities",
        ],
        postedAt: "2025-03-16T13:30:00Z",
        contact: "careers@clientcare.com",
    },
];

module.exports = jobs;
